# Generated by Django 4.2.17 on 2024-12-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='field',
            field=models.TextField(blank=True),
        ),
    ]
